### ISSUE TITLE
EACCESS spawn error with Firefox Developer Edition

### ISSUE THREAD

**Issue by cabbage** [karma-runner/karma-firefox-launcher#86]
Hi,
while updating the dependencies of my Angular project I wanted to change the browser of my Karma tests to Firefox Developer Edition. Unfortunately this lead to this error. 
Please let me know if I can provide any more information.

Cheers!

### Expected behaviour
Launch Karma with Firefox Developer Edition

### Actual behaviour
Launcher crashes after creating the temp dir. (Same with headless)
Interestingly with the standard Firefox I have no trouble launching the tests.

This is the crash log:
```
[36m08 04 2018 16:00:44.000:DEBUG [config]: [39mLoading config /Users/cab/Workspace/shard/lunar-shard/karma.conf.js
[36m08 04 2018 16:00:44.003:DEBUG [plugin]: [39mLoading inlined plugin (defining framework:jasmine).
[36m08 04 2018 16:00:44.003:DEBUG [plugin]: [39mLoading inlined plugin (defining launcher:Chrome, launcher:ChromeHeadless, launcher:ChromeCanary, launcher:ChromeCanaryHeadless, launcher:Chromium, launcher:ChromiumHeadless, launcher:Dartium, test).
[36m08 04 2018 16:00:44.003:DEBUG [plugin]: [39mLoading inlined plugin (defining launcher:Firefox, launcher:FirefoxHeadless, launcher:FirefoxDeveloper, launcher:FirefoxDeveloperHeadless, launcher:FirefoxAurora, launcher:FirefoxAuroraHeadless, launcher:FirefoxNightly, launcher:FirefoxNightlyHeadless).
[36m08 04 2018 16:00:44.003:DEBUG [plugin]: [39mLoading inlined plugin (defining reporter:kjhtml).
[36m08 04 2018 16:00:44.003:DEBUG [plugin]: [39mLoading inlined plugin (defining reporter:coverage-istanbul).
[36m08 04 2018 16:00:44.003:DEBUG [plugin]: [39mLoading inlined plugin (defining framework:@angular/cli, preprocessor:@angular/cli, reporter:@angular/cli, middleware:angularCliBlocker).
[36m08 04 2018 16:00:44.105:DEBUG [web-server]: [39mInstantiating middleware
[36m08 04 2018 16:00:44.106:DEBUG [reporter]: [39mTrying to load reporter: @angular/cli
[36m08 04 2018 16:00:44.106:DEBUG [reporter]: [39mTrying to load color-version of reporter: @angular/cli (@angular/cli_color)
[36m08 04 2018 16:00:44.106:DEBUG [reporter]: [39mCouldn't load color-version.
[36m08 04 2018 16:00:44.111:DEBUG [reporter]: [39mTrying to load reporter: kjhtml
[36m08 04 2018 16:00:44.111:DEBUG [reporter]: [39mTrying to load color-version of reporter: kjhtml (kjhtml_color)
[36m08 04 2018 16:00:44.114:DEBUG [reporter]: [39mCouldn't load color-version.
[36m08 04 2018 16:00:50.445:DEBUG [karma]: [39mList of files has changed, trying to execute
[33m08 04 2018 16:00:50.445:WARN [karma]: [39mNo captured browser, open http://localhost:9876/
[36m08 04 2018 16:00:50.448:DEBUG [watcher]: [39mWatching "/Users/cab/Workspace/shard/lunar-shard/src/favicon.ico"
[32m08 04 2018 16:00:50.449:INFO [karma]: [39mKarma v2.0.0 server started at http://0.0.0.0:9876/
[32m08 04 2018 16:00:50.450:INFO [launcher]: [39mLaunching browser FirefoxDeveloper with unlimited concurrency
[32m08 04 2018 16:00:50.452:INFO [launcher]: [39mStarting browser FirefoxDeveloper
[36m08 04 2018 16:00:50.453:DEBUG [temp-dir]: [39mCreating temp dir at /var/folders/ms/zrp2qb3j1fb51pbhmjst8vr40000gn/T/karma-29876120
[36m08 04 2018 16:00:50.453:DEBUG [launcher]: [39m/usr/local/Caskroom/firefox-developer-edition/latest http://localhost:9876/?id=29876120 -profile /var/folders/ms/zrp2qb3j1fb51pbhmjst8vr40000gn/T/karma-29876120 -no-remote
[31m08 04 2018 16:00:50.464:ERROR [karma]: [39m{ Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at spawnWithoutOutput (/Users/cab/Workspace/shard/lunar-shard/node_modules/karma/lib/launchers/process.js:168:24)
    at Object.ProcessLauncher._execCommand (/Users/cab/Workspace/shard/lunar-shard/node_modules/karma/lib/launchers/process.js:76:21)
    at Object.FirefoxBrowser._start (/Users/cab/Workspace/shard/lunar-shard/node_modules/karma-firefox-launcher/index.js:146:10)
    at Object.<anonymous> (/Users/cab/Workspace/shard/lunar-shard/node_modules/karma/lib/launchers/process.js:19:10)
    at emitOne (events.js:121:20)
    at Object.emit (events.js:211:7)
    at Object.BaseLauncher.start (/Users/cab/Workspace/shard/lunar-shard/node_modules/karma/lib/launchers/base.js:42:10)
    at Object.j (/Users/cab/Workspace/shard/lunar-shard/node_modules/karma/lib/launcher.js:117:17)
    at Object.setTimeout.bind.j (/Users/cab/Workspace/shard/lunar-shard/node_modules/qjobs/qjobs.js:143:18)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
[36m08 04 2018 16:00:50.467:DEBUG [launcher]: [39mDisconnecting all browsers
```

This is the log with the standard Firefox edition:

```
08 04 2018 16:08:26.130:DEBUG [config]: Loading config /Users/cab/Workspace/shard/lunar-shard/karma.conf.js
08 04 2018 16:08:26.134:DEBUG [plugin]: Loading inlined plugin (defining framework:jasmine).
08 04 2018 16:08:26.134:DEBUG [plugin]: Loading inlined plugin (defining launcher:Chrome, launcher:ChromeHeadless, launcher:ChromeCanary, launcher:ChromeCanaryHeadless, launcher:Chromium, launcher:ChromiumHeadless, launcher:Dartium, test).
08 04 2018 16:08:26.134:DEBUG [plugin]: Loading inlined plugin (defining launcher:Firefox, launcher:FirefoxHeadless, launcher:FirefoxDeveloper, launcher:FirefoxDeveloperHeadless, launcher:FirefoxAurora, launcher:FirefoxAuroraHeadless, launcher:FirefoxNightly, launcher:FirefoxNightlyHeadless).
08 04 2018 16:08:26.134:DEBUG [plugin]: Loading inlined plugin (defining reporter:kjhtml).
08 04 2018 16:08:26.134:DEBUG [plugin]: Loading inlined plugin (defining reporter:coverage-istanbul).
08 04 2018 16:08:26.134:DEBUG [plugin]: Loading inlined plugin (defining framework:@angular/cli, preprocessor:@angular/cli, reporter:@angular/cli, middleware:angularCliBlocker).
 10% building modules 1/1 modules 0 active08 04 2018 16:08:26.236:DEBUG [web-server]: Instantiating middleware
08 04 2018 16:08:26.237:DEBUG [reporter]: Trying to load reporter: @angular/cli
08 04 2018 16:08:26.237:DEBUG [reporter]: Trying to load color-version of reporter: @angular/cli (@angular/cli_color)
08 04 2018 16:08:26.237:DEBUG [reporter]: Couldn't load color-version.
08 04 2018 16:08:26.242:DEBUG [reporter]: Trying to load reporter: kjhtml
08 04 2018 16:08:26.243:DEBUG [reporter]: Trying to load color-version of reporter: kjhtml (kjhtml_color)
08 04 2018 16:08:26.243:DEBUG [reporter]: Couldn't load color-version.
08 04 2018 16:08:32.651:DEBUG [karma]: List of files has changed, trying to execute
08 04 2018 16:08:32.651:WARN [karma]: No captured browser, open http://localhost:9876/
08 04 2018 16:08:32.654:DEBUG [watcher]: Watching "/Users/cab/Workspace/shard/lunar-shard/src/favicon.ico"
08 04 2018 16:08:32.656:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
08 04 2018 16:08:32.656:INFO [launcher]: Launching browser Firefox with unlimited concurrency
08 04 2018 16:08:32.659:INFO [launcher]: Starting browser Firefox
08 04 2018 16:08:32.659:DEBUG [temp-dir]: Creating temp dir at /var/folders/ms/zrp2qb3j1fb51pbhmjst8vr40000gn/T/karma-22664961
08 04 2018 16:08:32.660:DEBUG [launcher]: /Applications/Firefox.app/Contents/MacOS/firefox-bin http://localhost:9876/?id=22664961 -profile /var/folders/ms/zrp2qb3j1fb51pbhmjst8vr40000gn/T/karma-22664961 -no-remote
08 04 2018 16:08:39.405:DEBUG [web-server]: serving: /Users/cab/Workspace/shard/lunar-shard/node_modules/karma/static/client.html
...
```

### Environment Details

- node: v8.11.1
- Karma: 2.0.0
- karma-firefox-launcher: 1.1.0
- Angular CLI: 1.6.8
- OS: macOS 10.12.6
- Relevant part of your `karma.config.js` file:
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-firefox-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: true,
    browsers: ['FirefoxDeveloper'],
    singleRun: false
  });
};
```

### Steps to reproduce the behaviour

1. Install dependency and require `karma-firefox-launcher` in Karma config file
2. Set `browsers: ['FirefoxDeveloper']` in Karma config file
3. Run Karma (in my case the Angular CLI does that)

**Comment by cabbage** [comment]
Alright I already found the issue. 
I used `brew cask` to install Firefox Devloper Edition and when I was prompted to set the `FIREFOX_DEVELOPER_BIN` env variable I ran `brew cask info firefox-developer-edition` which prompted (besides other info) the install path, which is `/usr/local/Caskroom/firefox-developer-edition/latest`. I used this path as is.
Now, when I took another look at the log at the log of the standard Firefox I noticed the path (`/Applications/Firefox.app/Contents/MacOS/firefox-bin`) and of course, macOS .app files are no executables and that's why I assume you can't launch that to spawn the application.

So, setting `FIREFOX_DEVELOPER_BIN=/Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox-bin` fixed it.
