### ISSUE TITLE
Karma and Selenium GRID 3.11

### ISSUE THREAD

**Issue by gregall** [karma-runner/karma-firefox-launcher#87]
Hi,

When im executing test code on "Selenium Grid" in version 3.11 i'm having an error

```
22 05 2018 15:08:57.971:DEBUG [launcher]: Finished all browsers
Error: [init({"platform":"LINUX","testName":"Karma test","tags":[],"version":"59","base":"WebDriver","browserName":"firefox"})] The environment you requested was unavailable.
undefined
    at /tmp/<MY_PROJECT>/node_modules/wd/lib/webdriver.js:134:15
    at Request._callback (/tmp/<MY_PROJECT>/node_modules/wd/lib/http-utils.js:89:7)
    at Request.self.callback (/tmp/<MY_PROJECT>/node_modules/wd/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/tmp/<MY_PROJECT>/node_modules/wd/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/tmp/<MY_PROJECT>/node_modules/wd/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

My test file:
```
        ....
        browsers: ['FirefoxHeadlessBrowser'],
        customLaunchers: {
            FirefoxHeadlessBrowser: {
                base: 'WebDriver',
                platform: 'LINUX',
                config: seleniumGridConfig,
                browserName: 'firefox',
                flags: ['-headless'],
                version: '59',
          ....
```

Json on Grid site:
```
14:52:01.015 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {base: WebDriver, browserName: firefox, flags: [-headless], javascriptEnabled: true, platform: LINUX, tags: [], testName: Karma test, version: 59}
14:52:01.017 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=7b519250-c385-4008-81b4-80c9f4f16f84, seleniumProtocol=WebDriver, marionette=true, cleanSession=true, version=59, platform=LINUX, acceptSslCerts=true, acceptInsecureCerts=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, maxInstances=8, platformName=LINUX}
2018-05-22 14:52:03.278:WARN:osjs.HttpChannel:qtp330382173-6937: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request:

```

On Selenium Grid 2.x everything is ok, is `karma-firefox-launcher` compatible with Grid 3.x?
Maybe my config is missing something? But for chrome browser it is working fine.

Thx!

**Comment by futchas** [comment]
+1 for this! Looks like the same problem I encounter:

```13:51:11 [test-karma] [32m15 06 2018 13:51:10.221:INFO [karma]: [39mKarma v2.0.0 server started at http://0.0.0.0:9876/
13:51:11 [test-karma] [32m15 06 2018 13:51:10.222:INFO [launcher]: [39mLaunching browsers customFirefox, customChrome with unlimited concurrency
13:51:11 [test-karma] [32m15 06 2018 13:51:10.228:INFO [launcher]: [39mStarting browser firefox via Remote WebDriver
13:51:11 [test-karma] [32m15 06 2018 13:51:10.275:INFO [launcher]: [39mStarting browser chrome via Remote WebDriver

13:51:13 [test-karma] [31m15 06 2018 13:51:13.320:ERROR [karma]: [39m{ Error: [init({"platform":"ANY","testName":"Karma test","tags":[],"version":"55.0.3","base":"WebDriver","browserName":"firefox","name":"Karma FF"})] 
13:51:13 [test-karma] undefined
13:51:13 [test-karma]     at /home/jenkins-slave/workspace/dsl/Karma/client/node_modules/wd/lib/webdriver.js:134:15
13:51:13 [test-karma]     at Request._callback (/home/jenkins-slave/workspace/dsl/Karma/client/node_modules/wd/lib/http-utils.js:88:7)
13:51:13 [test-karma]     at Request.self.callback (/home/jenkins-slave/workspace/dsl/Karma/client/node_modules/wd/node_modules/request/request.js:186:22)
13:51:13 [test-karma]     at emitTwo (events.js:106:13)
13:51:13 [test-karma]     at Request.emit (events.js:191:7)
13:51:13 [test-karma]     at Request.<anonymous> (/home/jenkins-slave/workspace/dsl/Karma/client/node_modules/wd/node_modules/request/request.js:1081:10)
13:51:13 [test-karma]     at emitOne (events.js:96:13)
13:51:13 [test-karma]     at Request.emit (events.js:188:7)
13:51:13 [test-karma]     at IncomingMessage.<anonymous> (/home/jenkins-slave/workspace/dsl/Karma/client/node_modules/wd/node_modules/request/request.js:1001:12)
13:51:13 [test-karma]     at IncomingMessage.g (events.js:292:16)
13:51:13 [test-karma]     at emitNone (events.js:91:20)
13:51:13 [test-karma]     at IncomingMessage.emit (events.js:185:7)
13:51:13 [test-karma]     at endReadableNT (_stream_readable.js:978:12)
13:51:13 [test-karma]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
13:51:13 [test-karma]     at process._tickCallback (internal/process/next_tick.js:104:9)```

**Comment by Kalste** [comment]
Did you find a solution?
I have the same error with Selenium Grid 3.14.

**Comment by futchas** [comment]
No solution so far unfortunately
